services:
  frontend:
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    networks:
      - app-network
    environment:
      - DJANGO_SETTINGS_MODULE=PriceMatch.settings
      - PYTHONUNBUFFERED=1
    container_name: backend

networks:
  app-network:
    driver: bridge