# Generated by Django 5.1.4 on 2024-12-23 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_jdcookie_sncookie_vphcookie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="user_id",
        ),
    ]
