# Generated by Django 5.1.4 on 2024-12-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_id_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="good_link",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
