# Generated by Django 5.1.4 on 2024-12-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_goods_good_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="good_platform",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
