# Generated by Django 5.1.4 on 2024-12-22 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                ("good_id", models.AutoField(primary_key=True, serialize=False)),
                ("good_name", models.CharField(max_length=255)),
                ("good_description", models.TextField(null=True)),
                ("good_scale", models.CharField(max_length=255)),
                ("good_type", models.CharField(max_length=255)),
                ("good_pic", models.ImageField(null=True, upload_to="./images/")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("phone", models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("prise", models.FloatField()),
                (
                    "good_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.goods"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_good",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "good_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.goods"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
    ]
